#邮箱配置
spring:
  #  freemarker:
  #    template-loader-path: file:/templates/
  #邮箱配置
  mail:
    from: 1808870333@qq.com
    #邮件服务器地址
    host: smtp.qq.com
    #协议
    protocol: smtps
    #编码格式
    default-encoding: utf-8
    #授权码
    password:
    #邮箱地址
    username:
    # 端口号
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true

alarm:
  # 接收报警的用户邮箱，多个人时，使用英文逗号分隔
  user: